---
- name: Install git & create git server
  hosts: 127.0.0.1
  connection: local
  module_defaults:
    shell:
      chdir: ${HOME}
  # remote_user: noname
  become: yes
  tasks:
    - name: Install openssh-server
      apt:
        name: ssh
        state: latest

    - name: Install git
      apt:
        name: git
        state: latest
        update_cache: yes

    - name: Check if ssh service exists
      stat: path=/etc/init.d/ssh
      register: service_status

    - name: Stop ssh service
      service: name=ssh state=stopped
      when: service_status.stat.exists
      register: service_stopped

    - name: Start ssh service
      service: name=ssh state=started
      when: service_status.stat.exists
      register: service_started

    - name: Create git user
      user:
        name: git

    - name: Create ssh directory
      ansible.builtin.file:
        path: /home/git/.ssh
        state: directory
        mode: "0755"

    - name: Copy ssh keys to git user
      ansible.builtin.copy:
        src: /.ssh/authorized_keys
        dest: /home/git/.ssh/authorized_keys
        owner: git
        mode: "0700"

    - name: Create passwords git directory
      ansible.builtin.file:
        path: /home/git/passwords.git
        state: directory
        mode: "0755"

    - name: Create a bare repository on the server
      command: git init --bare
      args:
        chdir: /home/git/passwords.git
      become_user: git

    - name: Add remote repository to local Git project
      command: git remote add origin git@10.26.92.138:/home/git/passwords.git
      args:
        chdir: /home/git/passwords.git

    - name: Push changes to the remote repository
      command: git push origin master
      args:
        chdir: /home/git/passwords.git
